feat: added Tiplink feature
sendaifun/solana-agent-kit pull request #40
Opened 2024-12-22 08:53 UTC by shivaji43

Added a Tiplink function where agent can create a tiplink for a given SOL amount  #21

2024-12-22 10:57 UTC, arihantbansal commented
Please create a langchain tool for Tiplink function in https://github.com/sendaifun/solana-agent-kit/blob/main/src/langchain/index.ts and export it via `createSolanaTools`

2024-12-22 15:56 UTC, shivaji43 commented
@arihantbansal Please take a look if everything is correct

2024-12-22 19:10 UTC, arihantbansal requested changes

2024-12-22 19:10 UTC, arihantbansal commented on src/langchain/index.ts
> +import { TipLink } from "@tiplink/api"
why is this import needed?

2024-12-23 05:52 UTC, thearyanag commented
hey @shivaji43 - can you modify the code to also support SPL tokens?

2024-12-23 10:30 UTC, shivaji43 commented
> hey @shivaji43 - can you modify the code to also support SPL tokens? 

Yes I will do that

2024-12-24 11:31 UTC, shivaji43 commented
@thearyanag please take a look

2024-12-24 23:28 UTC, thearyanag commented
can you pls rebase the branch

2024-12-24 23:29 UTC, thearyanag commented
@shivaji43 has this code being tested?

2024-12-24 23:30 UTC, thearyanag commented on src/langchain/index.ts
> +      const { url, signature } = await this.solanaKit.createTiplink(amountSol);
splMintAddress is part of the func, but not getting passed even :/ 

pls test the code before raising a PR

2024-12-26 06:30 UTC, shivaji43 commented on src/langchain/index.ts
> +      const { url, signature } = await this.solanaKit.createTiplink(amountSol);
I'm sorry , I will do the changes today test the code and then ask for review

2024-12-26 06:55 UTC, closed without merging

2024-12-26 06:56 UTC, shivaji43 commented on src/langchain/index.ts
> +      const { url, signature } = await this.solanaKit.createTiplink(amountSol);
I will try to make a new pull request , I have tested the code and it is working