Added Rock paper scissors blink to the solana agent kit
sendaifun/solana-agent-kit pull request #42
Opened 2024-12-22 14:02 UTC by The-x-35

2024-12-22 14:07 UTC, arihantbansal requested changes

2024-12-22 14:07 UTC, arihantbansal commented on package.json
> +    "@solana/actions": "^1.6.6",
pls remove this dep

2024-12-22 14:07 UTC, arihantbansal commented on package.json
> +  "packageManager": "pnpm@9.5.0+sha256.dbdf5961c32909fb030595a9daa1dae720162e658609a8f92f2fa99835510ca5"
this as well

2024-12-22 14:07 UTC, arihantbansal commented on src/tools/rps.ts
pls lint this file. otherwise I shall. (linting is not setup on repo but just use default prettier from vscode).

2024-12-22 14:07 UTC, arihantbansal commented on src/tools/rps.ts
> +import dotenv from "dotenv";
pls don't reference env vars directly inside fn, instead if needed use them as inputs to fn.

2024-12-22 14:07 UTC, arihantbansal commented on src/tools/rps.ts
> +import dotenv from "dotenv";
also, why is the env required here

2024-12-22 14:07 UTC, arihantbansal commented on src/tools/rps.ts
> +            `https://rps.sendarcade.fun${href}`,
it's a better practice to use `xyz.com/${args}`

2024-12-22 14:07 UTC, arihantbansal commented on src/tools/rps.ts
> +        const KEYPAIR = agent.wallet;
you don't need to redefine const for available variables here. just reference them directly. do the same everywhere else in this file as well.

2024-12-22 14:51 UTC, The-x-35 commented on src/tools/rps.ts
> +import dotenv from "dotenv";
i needed it previously during testing but we dont need it now, will remove it.

2024-12-22 14:52 UTC, The-x-35 commented on src/tools/rps.ts
> +            `https://rps.sendarcade.fun${href}`,
i know, but according to the href we are sending from the backend of the blink it will be like this only.
href is like, 
"/api/actions/outcome"
it has an extra / in the beginning.

2024-12-24 23:19 UTC, thearyanag commented on .env.example
why was this file deleted?

2024-12-24 23:20 UTC, thearyanag commented on src/langchain/index.ts
> +  description = `Gamble while playing rock paper scissors.
it's better to remove the word gamble, to avoid getting censored by models

2024-12-24 23:21 UTC, thearyanag commented on src/tools/index.ts
> +export * from "./rps";
change it to rock_paper_scissor

2024-12-24 23:21 UTC, thearyanag commented on src/tools/rps.ts
> +export async function rps(
fullform of res

2024-12-24 23:22 UTC, thearyanag commented on src/tools/rps.ts
> +                { commitment: 'confirmed', skipPreflight: true }
is skipPreflight true on purpose?

2024-12-24 23:23 UTC, thearyanag commented on src/tools/rps.ts
> +            `https://rps.sendarcade.fun${href}`,
@The-x-35 yeah but better to have 

href = "api/actions/outcome"

`https://rps.sendarcade.fun/${href}`,

as arihant mentioned 

looks clean to read

2024-12-25 05:14 UTC, The-x-35 commented on src/tools/rps.ts
> +            `https://rps.sendarcade.fun${href}`,
@thearyanag Sorry I can't change that part, its how the blink works, we will have to keep it like this to implement action chaining.
If you wish I can trim the href, first character and then do it like this, but that's quite unnecessary. We can just add a comment that it is like this.

2024-12-25 05:15 UTC, The-x-35 commented on .env.example
ahh sorry, instead of copying that, i just renamed that to .env.
I will correct it in the new commit.

2024-12-25 05:19 UTC, The-x-35 commented on src/tools/rps.ts
> +                { commitment: 'confirmed', skipPreflight: true }
umm, i just did it during testing to save time, will remove it.

2024-12-25 13:21 UTC, thearyanag commented on src/tools/rps.ts
> +            `https://rps.sendarcade.fun${href}`,
what do you mean by that's how blink work?

2024-12-27 19:34 UTC, merged